# Generated by Django 4.1 on 2022-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='workout date')),
                ('program_name', models.CharField(max_length=200)),
                ('program_phase', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('workout_type', models.CharField(choices=[(0, 'Strength'), (1, 'Conditioning'), (2, 'Active rest')], default=2, max_length=200)),
                ('time_start_end', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('total_sets', models.IntegerField(blank=True, null=True)),
                ('total_reps', models.IntegerField(blank=True, null=True)),
                ('average_weight', models.FloatField(blank=True, null=True)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
