# Generated by Django 4.1 on 2022-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='workout_type',
            field=models.CharField(choices=[('0', 'Strength'), ('1', 'Conditioning'), ('2', 'Active rest')], default='2', max_length=200),
        ),
    ]
